import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('ar'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  String tr(String key) {
    final Map<String, String>? currentLocaleTranslations = _localizedValues[locale.languageCode];
    if (currentLocaleTranslations != null && currentLocaleTranslations.containsKey(key)) {
      return currentLocaleTranslations[key]!;
    }
    // Fallback to Arabic if key is missing in French
    if (_localizedValues['ar']!.containsKey(key)) {
      return _localizedValues['ar']![key]!;
    }
    // If not found at all, return the key itself so developer knows it's missing
    return key;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'appName': 'رائد',
      // Sidebar / Navigation
      'dashboard': 'الرئيسية',
      'products': 'إدارة المنتجات',
      'inventory': 'المخزن',
      'sales': 'المبيعات اليومية',
      'invoices': 'الفواتير',
      'customers': 'العملاء',
      'statement': 'كشف الحساب',
      'debtors': 'الديون المتبقية',
      'creditors': 'ديون الموردين',
      'expenses': 'المصروفات',
      'returns': 'المرتجعات',
      'archive': 'الأرشيف',
      'settings': 'الإعدادات',
      'userManagement': 'إدارة المستخدمين',
      'addUser': 'إضافة مستخدم جديد',
      'editUser': 'تعديل بيانات المستخدم',
      'userPermissions': 'صلاحيات المستخدم',
      'email': 'البريد الإلكتروني',
      'phone': 'رقم الهاتف',
      'status': 'الحالة',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'role': 'الدور',
      'admin': 'مدير النظام',
      'salesEmployee': 'موظف مبيعات',
      'stockEmployee': 'موظف مخزن',
      'accountant': 'محاسب',
      'permissionSales': 'الوصول للمبيعات',
      'permissionInvoices': 'إنشاء الفواتير',
      'permissionInventory': 'إدارة المخزن',
      'permissionReports': 'عرض التقارير',
      'permissionCustomers': 'إدارة العملاء',
      'permissionExpenses': 'إدارة المصروفات',
      'permissionSettings': 'الوصول للإعدادات',
      'userAddedSuccess': 'تم إضافة المستخدم بنجاح ✨',
      'userUpdatedSuccess': 'تم تحديث بيانات المستخدم ✨',
      'userDeletedSuccess': 'تم حذف المستخدم بنجاح 🗑️',
      'userError': 'حدث خطأ في معالجة البيانات ❌',
      'logout': 'تسجيل الخروج',
      'archiveSummary': 'مراجعة كافة العمليات التاريخية',
      'archiveSearchHint': 'بحث في الأرشيف...',
      'unknownOperation': 'عملية غير معروفة',
      'barcode': 'باركود',
      'account': 'الحساب',
      
      // Common
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'add': 'إضافة',
      'edit': 'تعديل',
      'delete': 'حذف',
      'search': 'بحث...',
      'print': 'طباعة',
      'export': 'تصدير',
      'confirm': 'تأكيد',
      'amountLabel': 'المبلغ',
      'statementLabel': 'البيان',
      'notes': 'ملاحظات',
      'close': 'إغلاق',
      'date': 'التاريخ',
      'time': 'الوقت',
      
      // Auth / Login
      'loginTitle': 'تسجيل الدخول',
      'loginSubtitle': 'مرحباً بك في نظام رائد',
      'usernamePlace': 'اسم المستخدم',
      'passwordPlace': 'كلمة المرور',
      'loginButton': 'دخول للنظام',
      'invalidLogin': 'بيانات الدخول غير صحيحة',
      'usernameLabel': 'اسم المستخدم',
      'rememberMe': 'البقاء مسجلاً',
      'passwordLabel': 'كلمة المرور',

      // Dashboard
      'businessOverview': 'نظرة عامة',
      'salesToday': 'مبيعات اليوم',
      'expensesToday': 'مصروفات اليوم',
      'totalProducts': 'إجمالي المنتجات',
      'last7Days': 'أخر 7 أيام',
      'last30Days': 'أخر 30 يوم',
      'recentActivity': 'النشاطات الأخيرة',
      'quick_actions': 'الإجراءات السريعة',
      
      // Invoices & POS
      'selectCustomer': 'اختر العميل',
      'generalCustomer': 'عميل عام',
      'addToCart': 'إضافة',
      'cartCount': 'الأصناف المختارة',
      'total': 'الإجمالي',
      'paymentMethod': 'طريقة الدفع',
      'cash': 'نقدي (كاش)',
      'debt': 'آجل (دين)',
      'checkout': 'دفع',
      'invoiceNumber': 'رقم الفاتورة',
      'productName': 'اسم المنتج',
      'price': 'السعر',
      'qty': 'الكمية',
      'subtotal': 'المجموع الفرعي',
      'discount': 'الخصم',
      'tax': 'الضريبة',
      
      // Products
      'productCode': 'كود المنتج',
      'purchasePrice': 'سعر الشراء',
      'sellPrice': 'سعر البيع',
      'availableQty': 'الكمية المتوفرة',
      'addNewProduct': 'إضافة منتج جديد',
      
      // Expenses
      'expenseTitle': 'عنوان المصروف',
      'addNewExpense': 'إضافة مصروف جديد',
      
      // Settings
      'appSettings': 'إعدادات التطبيق',
      'language': 'اللغة / Language',
      'appearance': 'المظهر',
      'systemInfo': 'معلومات النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'system_theme': 'تلقائي (حسب النظام)',
      'dataSync': 'مزامنة البيانات',
      'syncNow': 'مزامنة الآن',
      'syncSuccess': 'تمت المزامنة بنجاح ✨',
      'syncFailed': 'فشل الاتصال بالخادم ❌',
      'lastSync': 'آخر مزامنة',
      'never': 'أبداً',
      'syncSubtitle': 'تحديث كافة البيانات من السحابة',
      
      // Customers & Debts
      'customerName': 'اسم العميل',
      'phoneNum': 'رقم الهاتف',
      'addressLocation': 'العنوان',
      'currentDebt': 'الديون الحالية',
      'remaining': 'المتبقي',
      
      // Statements & Reports
      'totalPurchases': 'إجمالي المشتريات',
      'totalPayments': 'إجمالي الدفعات',
      'accountStatement': 'كشف حساب',
      
      // New Keys
      'manageExpenses': 'إدارة التكاليف والتدفقات الخارجة',
      'totalExpenses': 'إجمالي المصروفات',
      'noExpenses': 'لا يوجد مصروفات مسجلة حالياً',
      'noDescription': 'بدون وصف',
      'fillRequired': 'يرجى ملء جميع الحقول المطلوبة',
      'saveFailed': 'فشل حفظ البيانات',
      'confirmDelete': 'هل أنت متأكد من الحذف؟',
      'description': 'الوصف / البيان',
      'amount': 'المبلغ',
      'category': 'التصنيف',
      'statementSummary': 'ملخص الحركات المالية للكيان',
      'noDataToPrint': 'لا توجد بيانات للطباعة',
      'selectEntityToViewStatement': 'الرجاء اختيار عميل أو مورد لعرض كشف الحساب',
      'selectEntity': 'اختر العميل / المورد',
      'operationLog': 'السجل العملياتي',
      'debit': 'عليه (مدين)',
      'credit': 'له (دائن)',
      'financialPosition': 'صافي المركز المالي',
      'requiredPayment': 'مطلوب منه سداد',
      'owedAmounts': 'يستحق له مبالغ',
      'balancedAccount': 'الحساب متزن',
      'debtInvoice': 'فاتورة مبيعات (آجل)',
      'cashSale': 'فاتورة مبيعات (نقدي)',
      'saleReturn': 'مرتجع مبيعات',
      'purchaseInvoice': 'فاتورة مشتريات',
      'paymentCollection': 'تحصيل دفعة (سداد)',
      'paymentToSupplier': 'تسديد دفعة للمورد',
      'purchaseReturn': 'مرتجع مشتريات',
      'debtBreakdown': 'تحليل المديونية (FIFO)',
      'paidCash': 'مدفوع نقداً',
      'reportsSummary': 'تحليل الأداء المالي والنمو',
      'weekly': 'أسبوعي',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'totalSales': 'إجمالي المبيعات',
      'netProfit': 'صافي الربح',
      'salesGrowth': 'نمو المبيعات',
      'live': 'مباشر',
      'noData': 'لا توجد بيانات',
      'topSellingProducts': 'أعلى المنتجات مبيعاً',
      'viewAll': 'عرض الكل',
      'fromPrev': 'عن الفترة السابقة',
      'underControl': 'تحت السيطرة',
      'excellentPerformance': 'أداء ممتاز ✨',
      'cashCustomer': 'عميل نقدي',
      'addedToCart': 'تمت إضافة للسلة',
      'productNotFound': 'المنتج غير موجود',
      'deleteInvoice': 'حذف الفاتورة',
      'confirmDeleteInvoice': 'هل أنت متأكد من حذف هذه الفاتورة؟ سيتم استرجاع الكميات للمخزون.',
      'saleSuccess': 'تم تسجيل الفاتورة وتحديث المخزون',
      'saleFailed': 'تعذر حفظ الفاتورة. تأكد من اتصالك بالخادم.',
      'pos': 'نقطة البيع',
      'invoiceHistory': 'سجل الفواتير',
      'quickSales': 'مبيعات سريعة',
      'financialArchive': 'الأرشيف المالي',
      'searchHint': 'بحث باسم المنتج أو الباركود...',
      'newSale': 'عملية بيع جديدة',
      'customer': 'العميل',
      'totalInvoice': 'إجمالي الفاتورة',
      'confirmSale': 'تأكيد البيع',
      'noSales': 'لا يوجد مبيعات مسجلة',
      'cart': 'سلة المبيعات',
      'items': 'أصناف',
      'invoiceDetail': 'تفاصيل الفاتورة',
      'completed': 'مكتملة',
      'soldProducts': 'المنتجات المبيعة',
      'unknownProduct': 'منتج غير معروف',
      'printInvoice': 'طباعة الفاتورة',
      'purchaseSuccess': 'تم تسجيل المشتريات وزيادة المخزون',
      'purchaseFailed': 'تعذر حفظ المشتريات',
      'purchasesCart': 'سلة الشراء',
      'selectSupplier': 'اختر المورد',
      'newPurchase': 'توريد جديد',
      'purchaseLog': 'سجل التوريد',
      'newInventoryAdd': 'إضافة سلع جديدة للمخزون',
      'reviewPastPurchases': 'مراجعة المشتريات السابقة',
      'supplierUnit': 'مورد',
      'purchase': 'توريد',
      'purchaseSearchHint': 'ابحث عن منتج للإيداع...',
      'current': 'الحالي',
      'noPurchaseHistory': 'لا يوجد سجل مشتريات',
      'value': 'قيمة',
      'depositPurchases': 'إيداع مشتريات',
      'totalDue': 'الإجمالي المستحق',
      'confirmDeposit': 'تأكيد الإيداع وزيادة المخزون',
      'supplier': 'المورد',
      'returnSuccess': 'تم تسجيل المرتجع وتحديث المخزون',
      'returnFailed': 'فشل تسجيل المرتجع',
      'newReturn': 'مرتجع جديد',
      'returnLog': 'سجل المرتجعات',
      'returnSummary': 'إدارة عمليات استرجاع المبيعات',
      'selectSaleItems': 'تحديد مواد المرتجع',
      'sold': 'المباع',
      'totalReturn': 'إجمالي المرتجع',
      'completeReturn': 'إتمام المرتجع',
      'noAvailableInvoices': 'لا يوجد فواتير متاحة',
      'emptyReturnHistory': 'سجل المرتجعات فارغ',
      'invoice': 'فاتورة',
      'return': 'مرتجع',
      'debtsAndReceivables': 'الديون والمستحقات',
      'debtSummary': 'متابعة الحسابات الآجلة والمديونيات',
      'usDebtors': 'لنا (مدينون)',
      'themCreditors': 'علينا (دائنون)',
      'collectPayment': 'تحصيل دفعة',
      'recordPayment': 'تسديد دفعة',
      'enterAmountToRecord': 'أدخل المبلغ المراد تسجيله:',
      'paymentFailed': 'فشل تسجيل الدفعة',
      'noCustomerDebts': 'لا يوجد مديونيات على العملاء',
      'noSupplierDebts': 'لا يوجد مبالغ مستحقة للموردين',
      'collect': 'تحصيل',
      'pay': 'تسديد',
      'debtorsClients': 'مدينون (عملاء)',
      'creditorsSuppliers': 'دائنون (موردين)',
      'unknown': 'غير معروف',
      'basicInfo': 'المعلومات الأساسية',
      'fullName': 'الاسم الكامل',
      'permissionType': 'نوع الصلاحية',
      'adminFull': 'مدير كامل',
      'staffLimited': 'موظف محدد',
      'logoutSummary': 'قم بتأمين حسابك بالخروج الآمن',
      'adminRole': 'مسؤول النظام',
      'activeMember': 'عضو مفعل',
      'user': 'مستخدم',
      'scanned': 'تم المسح',
      'smartScanner': 'الماسح الضوئي الذكي',
      'supplierNameRequired': 'اسم المورد مطلوب',
      'saveSupplierFailed': 'فشل حفظ بيانات المورد',
      'deleteSupplierTitle': 'حذف المورد',
      'deleteSupplierConfirm': 'هل أنت متأكد من حذف هذا المورد؟',
      'deleteSupplierFailed': 'فشل حذف المورد',
      'totalSuppliersCount': 'إجمالي الموردين',
      'supplierBalances': 'أرصدة الموردين',
      'noSuppliersFound': 'لا يوجد موردون مطابقون للبحث',
      'noPhone': 'بدون هاتف',
      'balanceLabel': 'الرصيد',
      'statementTooltip': 'كشف الحساب',
      'addNewSupplier': 'إضافة مورد جديد',
      'editSupplier': 'تعديل بيانات المورد',
      'manageSuppliers': 'إدارة الموردين والعمليات',
      'noName': 'بدون اسم',
      'quantity': 'الكمية',
      'fillRequiredFields': 'يرجى ملء جميع الحقول المطلوبة',
      'invalidQtyPrice': 'يرجى إدخال قيم صحيحة للكمية والسعر',
      'selectCustomerRequired': 'يرجى اختيار العميل',
      'optional': 'اختياري',
      'required': 'مطلوب',
      'confirmInput': 'تأكيد الإدخال',
      'confirmInvoice': 'تأكيد الفاتورة',
      'invoiceSaved': 'تم حفظ الفاتورة بنجاح',
      'quotation': 'عرض سعر',
      'creditInvoice': 'فاتورة شراء',
      'emailHint': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',

      // Alerts
      'confirmDeleteAction': 'هل أنت متأكد من الحذف؟',
      'successSale': 'تمت العملية بنجاح',
      'outOfStock': 'عفواً، نفدت الكمية',

      // New Premium Keys
      'notifications': 'التنبيهات',
      'new': 'جديد',
      'newActivity': 'عملية جديدة',
      'newSalesInvoice': 'تمت إضافة فاتورة مبيعات جديدة',
      'stockAlert': 'تنبيه مخزون',
      'lastUpdate': 'آخر تحديث للبيانات',
      'printReport': 'تصدير / طباعة التقرير',
      'salesAnalysis': 'تحليل النمو المالي',
      'dailyPerformance': 'أداء التدفقات النقدية اليومية',
      'topArticles': 'أعلى الأصناف',
      'mostSoldProducts': 'المنتجات الأكثر مبيعاً',
      'operationalEfficiency': 'مؤشرات الكفاءة التشغيلية',
      'liveStats': 'إحصائيات وقراءات حية',
      'activeInStock': 'منتج نشط بالمخزون',
      'customerBase': 'قاعدة العملاء',
      'registeredCustomers': 'عميل مسجل لدينا',
      'inactive30d': 'الخاملة (30 يوم)',
      'noRecentSales': 'منتجات لم تبع مؤخراً',
      'profitabilityAnalysis': 'تحليل الربحية',
      'netPerformance': 'مؤشر الأداء المالي الصافي',
      'profitMarginRatio': 'نسبة هامش الربح المحقق',
      'excellentPerf': 'أداء ممتاز',
      'goodPerf': 'أداء جيد',
      'targetLevel': 'المستوى المستهدف',
      'recordedTransactions': 'معاملة مسجلة',
      'exportExcel': 'تصدير Excel',
      'allTransactionTypes': 'جميع أنواع العمليات',
      'transaction': 'المعاملة',
      'clientDetails': 'البيان / العميل',
      'noTransactionsFound': 'لا توجد معاملات تطابق البحث',
      'generalStatement': 'بيان عام',
      'saleInvoice': 'فاتورة مبيعات',
      'operationalExpense': 'مصروف تشغيلي',
      'dueToUs': 'مستحقات لنا',
      'dueByUs': 'التزامات علينا',
      'noDebtRecords': 'لا توجد سجلات ديون في هذا القسم',
      'registerPayment': 'تسجيل دفعة',
      'paymentAmount': 'مبلغ الدفعة',
      'confirmSave': 'تأكيد الحفظ',
      'operationSuccess': 'عملية ناجحة ✨',
      'paymentRecordedSuccess': 'تم تسجيل الدفعة وتحديث الرصيد بنجاح',
      'operationFailed': 'فشل العملية ❌',
      'paymentRecordedFailed': 'حدث خطأ أثناء تسجيل الدفعة',
      'soldeRestant': 'المبلغ المتبقي',
      
      // Warehouses
      'warehouses': 'المستودعات',
      'manageWarehouses': 'إدارة المستودعات والمخازن',
      'totalWarehousesCount': 'إجمالي المستودعات',
      'warehouseName': 'اسم المستودع',
      'location': 'الموقع',
      'manager': 'المسؤول',
      'addNewWarehouse': 'إضافة مستودع جديد',
      'editWarehouse': 'تعديل بيانات المستودع',
      'warehouseNameRequired': 'اسم المستودع مطلوب',
      'saveWarehouseFailed': 'فشل حفظ بيانات المستودع',
      'deleteWarehouseTitle': 'حذف المستودع',
      'deleteWarehouseConfirm': 'هل أنت متأكد من حذف هذا المستودع؟',
      'deleteWarehouseFailed': 'فشل حذف المستودع',
      'noWarehousesFound': 'لا توجد مستودعات تطابق البحث',
      'warehouseUnit': 'مستودع',

      // Inventory
      'inventoryMovements': 'حركات المخزون',
      'transferStock': 'تحويل مخزون',
      'sourceWarehouse': 'المستودع المصدر',
      'destinationWarehouse': 'المستودع الوجهة',
      'qtyToTransfer': 'الكمية المراد تحويلها',
      'transferSuccess': 'تم التحويل بنجاح ✨',
      'transferFailed': 'فشل عملية التحويل ❌',
      'inventoryByWarehouse': 'المخزون حسب المستودع',
      'stockAddedSuccess': 'تمت إضافة المخزون بنجاح ✨',
      
      // Additional / Missing
      'error': 'خطأ',
      'retry': 'إعادة المحاولة',
      'loadingApp': 'جاري تحميل التطبيق...',
      'webviewError': 'خطأ في تهيئة WebView',
      'webviewMissing': 'WebView2 Runtime غير مثبت. يرجى تثبيته من موقع Microsoft.',
      'manageMoneySmart': 'إدارة أموالك بذكاء',
      'justNow': 'منذ قليل',
      'addExpense': 'تسجيل مصروف',
      'editExpense': 'تعديل مصروف',
      'general': 'عام',
      'deleteExpenseFailed': 'فشل حذف المصروف',
      'qtyPositive': 'الكمية يجب أن تكون أكبر من صفر',
      'luxuryBusiness': 'إدارة أعمالك بلمسة فخامة',
      'guestLogin': 'متابعة كضيف',
      'newAccount': 'حساب جديد',
      'fullNameLabel': 'الاسم الكامل',
      'joinUs': 'انضم إلينا لإدارة أعمالك بلمسة فخامة',
      'hasAccount': 'لديك حساب بالفعل؟ سجل دخولك',
      'registerButton': 'تسجيل الحساب',
      'saveProductFailed': '❌ فشل في حفظ بيانات المنتج',
      'initialStockDeposit': 'إيداع المخزون الأولي في:',
      'deleteProductFailedLinked': 'فشل الحذف. المنتج مرتبط بفواتير.',
      'stockShortage': 'نواقص المخزون',
      'productNameRequired': 'يرجى إدخال اسم المنتج',
      'confirmDeleteProduct': 'هل أنت متأكد من حذف هذا المنتج نهائياً؟',
      'stockValue': 'قيمة المخزون',
      'stockLabel': 'المخزون',
      'stockLog': 'سجل الحركات (المخزون)',
      'minStock': 'الحد الأدنى',
      'noMovements': 'لا توجد حركات مسجلة',
      'buyFromSupplier': 'شراء من مورد',
      'payment': 'سداد',
      'confirmSaleComplete': 'تأكيد وإتمام البيع',
      'cashMethod': 'نقدية',
      'debtMethod': 'بيع آجل (دين)',
      'amountAddedToCustomer': 'سيتم إضافة المبلغ لحساب العميل',
      'userPermissionsMgmt': 'إدارة المستخدمين والصلاحيات',
      'arabic': 'العربية',
      'customizeIdentity': 'تخصيص هوية التطبيق',
      'primaryColor': 'اللون الأساسي',
      'addCustomer': 'إضافة عميل جديد',
      'editCustomer': 'تعديل بيانات العميل',
      'inventoryValue': 'قيمة المخزون',
      'alert': 'تنبيه',
      'minAlert': 'الحد الأدنى للتنبيه',
      'noBarcode': 'بدون باركود',
      'productDetail': 'تفاصيل المنتج',
      'sedad': 'سداد',
      'bankily': 'Bankily',
      'masrvi': 'Masrvi',
      'amanty': 'Amanty',
      'click': 'Click',
      'bimbank': 'Bimbank',
      'gimtel': 'Gimtel',
      'french': 'الفرنسية',
      'returnSale': 'مرتجع مبيعات',
      'purchaseHistory': 'سجل التوريد',
      'addItemsToStock': 'إضافة سلع جديدة للمخزون',
      'fieldRequired': 'يرجى ملء هذا الحقل',
      'noResults': 'لا توجد نتائج',
      'errorLoadingData': 'خطأ في تحميل البيانات',
      'guest': 'زائر',
    },
    'fr': {
      'appName': 'Raid',
      // Sidebar / Navigation
      'dashboard': 'Accueil',
      'products': 'Produits',
      'inventory': 'Stock',
      'sales': 'Ventes Quotidiennes',
      'invoices': 'Factures',
      'customers': 'Clients',
      'statement': 'Relevé de Compte',
      'debtors': 'Débiteurs',
      'creditors': 'Créanciers',
      'expenses': 'Dépenses',
      'returns': 'Retours',
      'archive': 'Archives',
      'settings': 'Paramètres',
      'userManagement': 'Gestion des Utilisateurs',
      'addUser': 'Ajouter un utilisateur',
      'editUser': 'Modifier l\'utilisateur',
      'userPermissions': 'Permissions utilisateur',
      'email': 'E-mail',
      'phone': 'Téléphone',
      'status': 'Statut',
      'active': 'Actif',
      'inactive': 'Inactif',
      'role': 'Rôle',
      'admin': 'Administrateur',
      'salesEmployee': 'Employé de vente',
      'stockEmployee': 'Employé de stock',
      'accountant': 'Comptable',
      'permissionSales': 'Accès aux Ventes',
      'permissionInvoices': 'Créer des Factures',
      'permissionInventory': 'Gestion du Stock',
      'permissionReports': 'Voir les Rapports',
      'permissionCustomers': 'Gérer les Clients',
      'permissionExpenses': 'Gérer les Dépenses',
      'permissionSettings': 'Accès aux Paramètres',
      'userAddedSuccess': 'Utilisateur ajouté avec succès ✨',
      'userUpdatedSuccess': 'Utilisateur mis à jour ✨',
      'userDeletedSuccess': 'Utilisateur supprimé 🗑️',
      'userError': 'Erreur lors du traitement ❌',
      'logout': 'Déconnexion',
      'archiveSummary': 'Consulter l\'historique des opérations',
      'archiveSearchHint': 'Rechercher dans les archives...',
      'unknownOperation': 'Opération inconnue',
      'barcode': 'Code-barres',
      'account': 'Compte',
      'emailHint': 'Veuillez saisir l\'e-mail et le mot de passe',
      
      // Common
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'add': 'Ajouter',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'search': 'Rechercher...',
      'print': 'Imprimer',
      'export': 'Exporter',
      'confirm': 'Confirmer',
      'amountLabel': 'Montant',
      'statementLabel': 'Désignation',
      'notes': 'Notes',
      'close': 'Fermer',
      'date': 'Date',
      'time': 'Heure',
      
      // Auth / Login
      'loginTitle': 'Connexion',
      'loginSubtitle': 'Bienvenue dans le système Raid',
      'usernamePlace': 'Nom d\'utilisateur',
      'passwordPlace': 'Mot de passe',
      'loginButton': 'Se connecter',
      'invalidLogin': 'Identifiants incorrects',
      'usernameLabel': 'Nom d\'utilisateur',
      'rememberMe': 'Se souvenir de moi',
      'passwordLabel': 'Mot de passe',

      // Dashboard
      'businessOverview': 'Aperçu',
      'salesToday': 'Ventes d\'aujourd\'hui',
      'expensesToday': 'Dépenses d\'aujourd\'hui',
      'totalProducts': 'Total Produits',
      'last7Days': '7 derniers jours',
      'last30Days': '30 derniers jours',
      'recentActivity': 'Activité Récente',
      'quick_actions': 'Actions Rapides',
      
      // Invoices & POS
      'selectCustomer': 'Sélectionner Client',
      'generalCustomer': 'Client Général',
      'addToCart': 'Ajouter',
      'cartCount': 'Articles',
      'total': 'Total',
      'paymentMethod': 'Mode de Paiement',
      'cash': 'Espèces',
      'debt': 'Crédit (Dette)',
      'checkout': 'Payer',
      'invoiceNumber': 'Facture Nº',
      'productName': 'Nom du Produit',
      'price': 'Prix',
      'qty': 'Qté',
      'subtotal': 'Sous-total',
      'discount': 'Remise',
      'tax': 'TVA',
      
      // Products
      'productCode': 'Code Produit',
      'purchasePrice': 'Prix d\'Achat',
      'sellPrice': 'Prix de Vente',
      'availableQty': 'Qté Disponible',
      'addNewProduct': 'Ajouter Produit',
      
      // Expenses
      'expenseTitle': 'Libellé',
      'addNewExpense': 'Nouvelle Dépense',
      
      // Settings
      'appSettings': 'Paramètres de l\'Application',
      'language': 'Langue / Language',
      'appearance': 'Apparence',
      'systemInfo': 'Info Système',
      'light': 'Clair',
      'dark': 'Sombre',
      'system_theme': 'Système',
      'dataSync': 'Synchronisation',
      'syncNow': 'Synchroniser',
      'syncSuccess': 'Synchronisation réussie ✨',
      'syncFailed': 'Échec de connexion ❌',
      'lastSync': 'Dernière synchro',
      'never': 'Jamais',
      'syncSubtitle': 'Mettre à jour les données',
      
      // Customers & Debts
      'customerName': 'Nom du Client',
      'phoneNum': 'Téléphone',
      'addressLocation': 'Adresse',
      'currentDebt': 'Dette Actuelle',
      'remaining': 'Restant',
      
      // Statements & Reports
      'totalPurchases': 'Total Achats',
      'totalPayments': 'Total Paiements',
      'accountStatement': 'Relevé de Compte',
      
      // New Keys
      'manageExpenses': 'Gérer les coûts et les flux sortants',
      'totalExpenses': 'Total des Dépenses',
      'noExpenses': 'Aucune dépense enregistrée',
      'noDescription': 'Sans description',
      'fillRequired': 'Veuillez remplir tous les champs obligatoires',
      'saveFailed': 'Échec de l\'enregistrement des données',
      'confirmDelete': 'Êtes-vous sûr de vouloir supprimer ?',
      'description': 'Description / Libellé',
      'amount': 'Montant',
      'category': 'Catégorie',
      'statementSummary': 'Résumé des mouvements financiers de l\'entité',
      'noDataToPrint': 'Aucune donnée à imprimer',
      'selectEntityToViewStatement': 'Veuillez sélectionner un client ou fournisseur',
      'selectEntity': 'Choisir Client / Fournisseur',
      'operationLog': 'Journal des opérations',
      'debit': 'Droit (Débit)',
      'credit': 'Avoir (Crédit)',
      'financialPosition': 'Position financière nette',
      'requiredPayment': 'Paiement requis',
      'owedAmounts': 'Montants dûs',
      'balancedAccount': 'Compte équilibré',
      'debtInvoice': 'Facture de vente (Crédit)',
      'cashSale': 'Facture de vente (Espèces)',
      'saleReturn': 'Retour de vente',
      'purchaseInvoice': 'Facture d\'achat',
      'paymentCollection': 'Recouvrement de paiement',
      'paymentToSupplier': 'Paiement fournisseur',
      'purchaseReturn': 'Retour d\'achat',
      'debtBreakdown': 'Analyse de la dette (FIFO)',
      'paidCash': 'Payé en espèces',
      'reportsSummary': 'Analyse de la performance et de la croissance',
      'weekly': 'Hebdomadaire',
      'monthly': 'Mensuel',
      'yearly': 'Annuel',
      'totalSales': 'Total des Ventes',
      'netProfit': 'Bénéfice Net',
      'salesGrowth': 'Croissance des Ventes',
      'live': 'En direct',
      'noData': 'Aucune donnée',
      'topSellingProducts': 'Meilleures ventes',
      'viewAll': 'Voir tout',
      'fromPrev': 'par rapport à la période précédente',
      'underControl': 'Sous contrôle',
      'excellentPerformance': 'Excellente performance ✨',
      'cashCustomer': 'Client Espèces',
      'addedToCart': 'Ajouté au panier',
      'productNotFound': 'Produit non trouvé',
      'deleteInvoice': 'Supprimer Facture',
      'confirmDeleteInvoice': 'Êtes-vous sûr ? Les quantités seront retournées au stock.',
      'saleSuccess': 'Facture enregistrée et stock mis à jour',
      'saleFailed': 'Échec de l\'enregistrement. Vérifiez votre connexion.',
      'pos': 'Point de Vente',
      'invoiceHistory': 'Historique des Factures',
      'quickSales': 'Ventes Rapides',
      'financialArchive': 'Archives Financières',
      'searchHint': 'Rechercher par nom ou code...',
      'newSale': 'Nouvelle Vente',
      'customer': 'Client',
      'totalInvoice': 'Total Facture',
      'confirmSale': 'Confirmer Vente',
      'noSales': 'Aucune vente enregistrée',
      'cart': 'Panier de vente',
      'items': 'articles',
      'invoiceDetail': 'Détails de la Facture',
      'completed': 'Complétée',
      'soldProducts': 'Produits Vendus',
      'unknownProduct': 'Produit inconnu',
      'printInvoice': 'Imprimer la Facture',
      'purchaseSuccess': 'Achats enregistrés et stock mis à jour',
      'purchaseFailed': 'Échec de l\'enregistrement des achats',
      'purchasesCart': 'Panier d\'achat',
      'selectSupplier': 'Sélectionner Fournisseur',
      'newPurchase': 'Nouvel Approvisionnement',
      'purchaseLog': 'Historique d\'Approvisionnement',
      'newInventoryAdd': 'Ajouter de nouveaux articles au stock',
      'reviewPastPurchases': 'Consulter les achats passés',
      'supplierUnit': 'Fournisseur',
      'purchase': 'Achat',
      'purchaseSearchHint': 'Rechercher un produit à déposer...',
      'current': 'Actuel',
      'noPurchaseHistory': 'Aucun historique d\'achat',
      'value': 'Valeur',
      'depositPurchases': 'Dépôt d\'achats',
      'totalDue': 'Total Dû',
      'confirmDeposit': 'Confirmer le dépôt et augmenter le stock',
      'supplier': 'Fournisseur',
      'returnSuccess': 'Retour enregistré et stock mis à jour',
      'returnFailed': 'Échec de l\'enregistrement du retour',
      'newReturn': 'Nouveau Retour',
      'returnLog': 'Historique des Retours',
      'returnSummary': 'Gérer les retours de ventes',
      'selectSaleItems': 'Sélectionner les articles à retourner',
      'sold': 'Vendu',
      'totalReturn': 'Total Retour',
      'completeReturn': 'Compléter le retour',
      'noAvailableInvoices': 'Aucune facture disponible',
      'emptyReturnHistory': 'Historique des retours vide',
      'invoice': 'Facture',
      'return': 'Retour',
      'debtsAndReceivables': 'Dettes et Créances',
      'debtSummary': 'Suivi des comptes à crédit et des dettes',
      'usDebtors': 'À nous (Débiteurs)',
      'themCreditors': 'À nous (Créanciers)',
      'collectPayment': 'Encaisser un paiement',
      'recordPayment': 'Enregistrer un paiement',
      'enterAmountToRecord': 'Entrez le montant à enregistrer :',
      'paymentFailed': 'Échec de l\'enregistrement du paiement',
      'noCustomerDebts': 'Aucune dette client',
      'noSupplierDebts': 'Aucun montant dû aux fournisseurs',
      'collect': 'Encaisser',
      'pay': 'Payer',
      'debtorsClients': 'Débiteurs (Clients)',
      'creditorsSuppliers': 'Créanciers (Fournisseurs)',
      'unknown': 'Inconnu',
      'basicInfo': 'Informations de Base',
      'fullName': 'Nom Complet',
      'permissionType': 'Type de Permission',
      'adminFull': 'Administrateur Complet',
      'staffLimited': 'Personnel Limité',
      'logoutSummary': 'Sécurisez votre compte en vous déconnectant en toute sécurité',
      'adminRole': 'Administrateur Système',
      'activeMember': 'Membre Actif',
      'user': 'Utilisateur',
      'scanned': 'Scanné',
      'smartScanner': 'Scanner Intelligent',
      'supplierNameRequired': 'Nom du fournisseur requis',
      'saveSupplierFailed': 'Échec de l\'enregistrement du fournisseur',
      'deleteSupplierTitle': 'Supprimer le fournisseur',
      'deleteSupplierConfirm': 'Êtes-vous sûr de vouloir supprimer ce fournisseur ?',
      'deleteSupplierFailed': 'Échec de la suppression du fournisseur',
      'totalSuppliersCount': 'Total Fournisseurs',
      'supplierBalances': 'Soldes Fournisseurs',
      'noSuppliersFound': 'Aucun fournisseur trouvé',
      'noPhone': 'Sans téléphone',
      'balanceLabel': 'Solde',
      'statementTooltip': 'Relevé de compte',
      'addNewSupplier': 'Nouveau Fournisseur',
      'editSupplier': 'Modifier Fournisseur',
      'manageSuppliers': 'Gérer les fournisseurs',
      'noName': 'Sans nom',
      'quantity': 'Quantité',
      'fillRequiredFields': 'Remplissez tous les champs',
      'invalidQtyPrice': 'Quantité/Prix invalide',
      'selectCustomerRequired': 'Sélectionnez un client',
      'optional': 'Optionnel',
      'required': 'Requis',
      'confirmInput': 'Confirmer l\'entrée',
      'confirmInvoice': 'Confirmer la facture',
      'invoiceSaved': 'Facture enregistrée',
      'quotation': 'Devis',
      'creditInvoice': 'Facture d\'achat',

      // Alerts
      'confirmDeleteAction': 'Êtes-vous sûr de vouloir supprimer ?',
      'successSale': 'Opération réussie',
      'outOfStock': 'Rupture de stock',
      'notifications': 'Notifications',
      'new': 'Nouveau',
      'newActivity': 'Nouvelle activité',
      'newSalesInvoice': 'Nouvelle facture de vente ajoutée',
      'stockAlert': 'Alerte stock',
      'lastUpdate': 'Dernière mise à jour',
      'printReport': 'Exporter / Imprimer le rapport',
      'salesAnalysis': 'Analyse de la croissance financière',
      'dailyPerformance': 'Performance des flux quotidiens',
      'topArticles': 'Meilleurs articles',
      'mostSoldProducts': 'Produits les plus vendus',
      'operationalEfficiency': 'Indicateurs d\'efficacité',
      'liveStats': 'Statistiques en direct',
      'activeInStock': 'Produits actifs en stock',
      'customerBase': 'Base de clients',
      'registeredCustomers': 'Clients enregistrés',
      'inactive30d': 'Inactifs (30 jours)',
      'noRecentSales': 'Pas de ventes récentes',
      'profitabilityAnalysis': 'Analyse de rentabilité',
      'netPerformance': 'Performance financière nette',
      'profitMarginRatio': 'Marge bénéficiaire',
      'excellentPerf': 'Excellent rendement',
      'goodPerf': 'Bon rendement',
      'targetLevel': 'Niveau cible',
      'recordedTransactions': 'Transactions enregistrées',
      'exportExcel': 'Exporter Excel',
      'allTransactionTypes': 'Tous les types',
      'transaction': 'Transaction',
      'clientDetails': 'Client / Détails',
      'noTransactionsFound': 'Aucune transaction trouvée',
      'generalStatement': 'Général',
      'saleInvoice': 'Facture de vente',
      'operationalExpense': 'Frais Opérationnels',
      'dueToUs': 'À nous',
      'dueByUs': 'À payer',
      'noDebtRecords': 'Aucun enregistrement de dette',
      'registerPayment': 'Enregistrer paiement',
      'paymentAmount': 'Montant du paiement',
      'confirmSave': 'Confirmer',
      'operationSuccess': 'Opération réussie ✨',
      'paymentRecordedSuccess': 'Le paiement a été enregistré avec succès',
      'operationFailed': 'Opération échouée ❌',
      'paymentRecordedFailed': 'Erreur lors de l’enregistrement du paiement',
      'soldeRestant': 'Solde restant',
      
      // Additional / Missing
      'error': 'Erreur',
      'retry': 'Réessayer',
      'loadingApp': 'Chargement de l\'application...',
      'webviewError': 'Erreur d\'initialisation WebView',
      'webviewMissing': 'WebView2 Runtime non installé. Veuillez l\'installer depuis Microsoft.',
      'manageMoneySmart': 'Gérez votre argent intelligemment',
      'justNow': 'À l\'instant',
      'addExpense': 'Enregistrer une dépense',
      'editExpense': 'Modifier la dépense',
      'general': 'Général',
      'deleteExpenseFailed': 'Échec de la suppression de la dépense',
      'qtyPositive': 'La quantité doit être supérieure à zéro',
      'luxuryBusiness': 'Gérez votre entreprise avec une touche de luxe',
      'guestLogin': 'Continuer en tant qu\'invité',
      'newAccount': 'Nouveau compte',
      'fullNameLabel': 'Nom complet',
      'joinUs': 'Rejoignez-nous pour gérer votre entreprise avec luxe',
      'hasAccount': 'Vous avez déjà un compte ? Connectez-vous',
      'registerButton': 'Créer le compte',
      'saveProductFailed': '❌ Échec de l\'enregistrement du produit',
      'initialStockDeposit': 'Dépôt de stock initial dans :',
      'deleteProductFailedLinked': 'Échec de la suppression. Produit lié à des factures.',
      'stockShortage': 'Rupture de stock',
      'productNameRequired': 'Veuillez entrer le nom du produit',
      'confirmDeleteProduct': 'Voulez-vous vraiment supprimer ce produit définitivement ?',
      'stockValue': 'Valeur du stock',
      'stockLabel': 'Stock',
      'stockLog': 'Journal des mouvements (Stock)',
      'minStock': 'Stock Min',
      'noMovements': 'Aucun mouvement enregistré',
      'buyFromSupplier': 'Acheter chez un fournisseur',
      'payment': 'Paiement',
      'confirmSaleComplete': 'Confirmer et terminer la vente',
      'cashMethod': 'Espèces',
      'debtMethod': 'Vente à crédit (Dette)',
      'amountAddedToCustomer': 'Le montant sera ajouté au compte du client',
      'guest': 'Invité',
    }
  };
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ar', 'fr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsContext on BuildContext {
  String tr(String key) => AppLocalizations.of(this).tr(key);
}
